# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "21bb1c1cd18b274d753ca1444ab6ef24"
name = "new-payment-app"
handle = "new-payment-app-6"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "berrystore-02.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_customizations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
